# Generated by Django 4.2.26 on 2026-01-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
