# Generated by Django 4.2.26 on 2026-01-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at']},
        ),
    ]
