# Generated by Django 4.2.26 on 2025-12-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_author_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                to="blog.blogpost",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
            ),
        ),
    ]
