# Generated by Django 4.2.26 on 2026-01-17 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_blogpost_categories_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
