# Generated by Django 4.2.26 on 2025-12-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_post_to_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
