# Generated by Django 4.2.26 on 2026-01-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_unlikes_alter_blogpost_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='body',
        ),
    ]
