# Generated by Django 4.2.26 on 2026-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_updated_on_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
