# Generated by Django 4.2.26 on 2025-12-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_create_blogpost_likes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, unique=True),
        ),
    ]
