# Generated by Django 4.2.26 on 2025-12-23 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
