# Generated by Django 4.2.26 on 2026-01-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_blogpost_author_alter_blogpost_image_and_more"),
    ]

    operations = [
    ]
