# Generated by Django 4.2.26 on 2026-01-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_blogpost_is_success_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_success_story',
        ),
    ]
