# Generated by Django 4.2.26 on 2025-12-09 22:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0008_alter_subplanfeature_subplan'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=40, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_cart', models.TextField(blank=True, default='')),
                ('stripe_pid', models.CharField(blank=True, default='', max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(default=1)),
                ('lineitem_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_items', to='checkout.order')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subplan')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('lineitem_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
