# Generated by Django 5.2.1 on 2025-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
