# Generated by Django 5.2.1 on 2025-12-06 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_street_address1_order_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lineitems', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_lineitems', to='checkout.order'),
        ),
    ]
