# Generated by Django 5.2.1 on 2025-12-20 05:07

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
