# Generated by Django 5.2.1 on 2025-12-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_productlineitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_items', to='checkout.order'),
        ),
    ]
