# Generated by Django 4.2.26 on 2025-12-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplan',
            old_name='plan_price',
            new_name='price',
        ),
    ]
