# Generated by Django 4.2.26 on 2025-12-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_plan_price_subplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlight_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subplan',
            name='max_member',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subplan',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_months', models.PositiveIntegerField()),
                ('total_discount', models.PositiveIntegerField()),
                ('subplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='subscriptions.subplan')),
            ],
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(to='subscriptions.subplan'),
        ),
    ]
