# Generated by Django 4.2.26 on 2025-12-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subplan_highlight_status_subplan_max_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
