# Generated by Django 5.2.1 on 2025-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subplan_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandiscount',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
