# Generated by Django 5.2.1 on 2025-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_plandiscount_total_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandiscount',
            name='total_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plandiscount',
            name='total_months',
            field=models.IntegerField(),
        ),
    ]
