# Generated by Django 5.2.1 on 2025-12-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_plandiscount_total_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(related_name='features', to='subscriptions.subplan'),
        ),
    ]
