# Generated by Django 5.2.1 on 2025-12-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subplanfeature_subplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(to='subscriptions.subplan'),
        ),
    ]
