# Generated by Django 4.2.26 on 2025-11-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_date',
        ),
    ]
